{
 "title": "HAproxy Servers | HAproxy",
 "description": "HAproxy backend servers",
 "tags": [
  "haproxy",
  "servers"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,1h,6h,1d" },
   {
    "name": "alias",
    "label": "Load Balancer",
    "query": "label_values(haproxy_backend_status, instance)"
   },
   {
    "name": "backend",
    "label": "Backend",
    "query": "label_values(haproxy_backend_status, proxy)"
   },
   {
    "name": "server",
    "label": "Server",
    "query": "label_values(haproxy_server_bytes_in_total{proxy=~\"$backend\"}, server)"
   },
   {
    "name": "code",
    "label": "HTTP Code",
    "query": "label_values(haproxy_server_http_responses_total{proxy=~\"$backend\", server=~\"$server\"}, code)"
   }
  ]
 },
 "panels": [
  { "title": "Backend Responses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Response Times",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_response_time_average_seconds{proxy=~\"$backend\", instance=~\"$alias\"}",
     "legendFormat": "{{ proxy }}"
    }
   ]
  },
  {
   "title": "HTTP Responses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_http_responses_total{proxy=~\"$backend\", server=~\"$server\", code=~\"$code\", instance=\"$alias\"}[180s])",
     "legendFormat": "{{ proxy }}/{{ server }}/{{ code }}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Bytes IN",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_bytes_in_total{proxy=~\"$backend\", server=~\"$server\", instance=\"$alias\"}[180s])",
     "legendFormat": "{{ proxy }}/{{ server }}"
    }
   ]
  },
  {
   "title": "Bytes OUT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_bytes_out_total{proxy=~\"$backend\", server=~\"$server\", instance=\"$alias\"}[180s])",
     "legendFormat": "{{ proxy }}/{{ server }}"
    }
   ]
  },
  { "title": "Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Active Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_current_sessions{proxy=~\"$backend\", server=~\"$server\", instance=\"$alias\"}",
     "legendFormat": "{{ proxy }}/{{ server }}"
    }
   ]
  },
  {
   "title": "New Session Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_current_sessions{proxy=~\"$backend\", instance=\"$alias\"}",
     "legendFormat": "{{ proxy }}"
    }
   ]
  },
  {
   "title": "Max Active Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_max_sessions{proxy=~\"$backend\", server=~\"$server\", instance=\"$alias\"}",
     "legendFormat": "{{ proxy }}/{{ server }}"
    }
   ]
  },
  {
   "title": "Max Session Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_max_session_rate{proxy=~\"$backend\", server=~\"$server\", instance=\"$alias\"}",
     "legendFormat": "{{ proxy }}/{{ server }}"
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } }
 ]
}